[wokwi]
version = 1
firmware = './Build/sketch.ino.bin'
elf = './Build/sketch.ino.elf'
gdbServerPort=3333

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "device:80"